spring.application.name=FrontOffice
server.port=8080
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=balirambabar007@gmail.com
spring.mail.password=jlok cspy hyal ucvw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.profiles.active=dev

